# Generated by Django 4.1.7 on 2023-03-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emoney',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_id', models.BigIntegerField(null=True)),
                ('sales_id', models.BigIntegerField(null=True)),
                ('usage_date', models.DateTimeField(null=True)),
                ('customer_name', models.CharField(max_length=255, null=True)),
                ('usage_amount', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('cashier', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'e_money',
            },
        ),
        migrations.CreateModel(
            name='EMType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('partner', models.CharField(max_length=255, null=True)),
                ('item', models.CharField(max_length=255, null=True)),
                ('type_name', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'em_type',
            },
        ),
        migrations.CreateModel(
            name='FreeeDeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, null=True)),
                ('number', models.BigIntegerField(null=True)),
                ('title_row', models.CharField(max_length=255, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('slip_number', models.IntegerField(null=True)),
                ('debit_account', models.CharField(max_length=255, null=True)),
                ('debit_sub_account', models.CharField(max_length=255, null=True)),
                ('debit_partner', models.CharField(max_length=255, null=True)),
                ('debit_department', models.CharField(max_length=255, null=True)),
                ('debit_item', models.CharField(max_length=255, null=True)),
                ('debit_memo_tag', models.CharField(max_length=255, null=True)),
                ('debit_tax_category', models.CharField(max_length=255, null=True)),
                ('debit_amount', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('debit_tax_amount', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('credit_account', models.CharField(max_length=255, null=True)),
                ('credit_sub_account', models.CharField(max_length=255, null=True)),
                ('credit_partner', models.CharField(max_length=255, null=True)),
                ('credit_department', models.CharField(max_length=255, null=True)),
                ('credit_item', models.CharField(max_length=255, null=True)),
                ('credit_memo_tag', models.CharField(max_length=255, null=True)),
                ('credit_tax_category', models.CharField(max_length=255, null=True)),
                ('credit_amount', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('credit_tax_amount', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('summary', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'freee_deals',
            },
        ),
        migrations.CreateModel(
            name='Hp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sales_id', models.BigIntegerField(null=True)),
                ('sales_date', models.DateTimeField(null=True)),
                ('net_sales', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('points', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'hp',
            },
        ),
        migrations.CreateModel(
            name='Omron',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('handling_date', models.DateTimeField(null=True)),
                ('credit_company_code', models.CharField(max_length=255, null=True)),
                ('credit_company_name', models.CharField(max_length=255, null=True)),
                ('payment_category', models.CharField(max_length=255, null=True)),
                ('payment_name', models.CharField(max_length=255, null=True)),
                ('installment_count_gift_value', models.IntegerField(null=True)),
                ('gift_count', models.IntegerField(null=True)),
                ('slip_number', models.CharField(max_length=255, null=True)),
                ('sales_amount', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('scheduled_payment_date1', models.DateTimeField(null=True)),
                ('scheduled_payment_date2', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'omron',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('sales_id', models.BigIntegerField(null=True)),
                ('date', models.DateTimeField(null=True)),
                ('time', models.DateTimeField(null=True)),
                ('total_collected', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('net_total', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('customer_name', models.CharField(max_length=255, null=True)),
                ('card_brand', models.CharField(max_length=255, null=True)),
                ('pan_suffix', models.CharField(max_length=255, null=True)),
                ('deposit_date', models.CharField(max_length=255, null=True)),
                ('fee_percentage_rate', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('field1', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='RetailItems',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255, null=True)),
                ('number', models.IntegerField(null=True)),
                ('display_name', models.CharField(max_length=255, null=True)),
                ('norm_name', models.CharField(max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('vat_type', models.CharField(max_length=255, null=True)),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('product_category', models.CharField(max_length=255, null=True)),
                ('supplier_name', models.CharField(max_length=255, null=True)),
                ('seller', models.BigIntegerField(null=True)),
                ('active', models.BooleanField(null=True)),
                ('registration_date', models.DateTimeField(null=True)),
                ('update_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'retail_items',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sales_id', models.CharField(max_length=255, null=True)),
                ('customer', models.CharField(max_length=255, null=True)),
                ('sales_date', models.DateTimeField(null=True)),
                ('from_date', models.DateTimeField(null=True)),
                ('to_date', models.DateTimeField(null=True)),
                ('gross_salon_sales', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('gross_retail_sales', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('total_gross_sales', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('total_salon_discount', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('retail_discount', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('service_net_sales', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('retail_net_sales', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('total_net_sales', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('card', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('card_type', models.CharField(max_length=255, null=True)),
                ('em', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('prepaid', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('comment', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'sales',
            },
        ),
        migrations.CreateModel(
            name='SalesDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sale_id', models.BigIntegerField(null=True)),
                ('payment_id', models.BigIntegerField(null=True)),
                ('customer', models.CharField(max_length=255, null=True)),
                ('item_type', models.CharField(max_length=255, null=True)),
                ('item_id', models.BigIntegerField(null=True)),
                ('staff', models.CharField(max_length=255, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('gross_sales', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('discount_type', models.CharField(max_length=255, null=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('net_sales', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('field1', models.CharField(max_length=255, null=True)),
                ('field2', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'sales_details',
            },
        ),
        migrations.CreateModel(
            name='Saller',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('saller_name', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'saller',
            },
        ),
        migrations.CreateModel(
            name='SalonItems',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255, null=True)),
                ('number', models.IntegerField(null=True)),
                ('display_name', models.CharField(max_length=255, null=True)),
                ('norm_name', models.CharField(max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('tax_category', models.CharField(max_length=255, null=True)),
                ('active', models.BooleanField(null=True)),
                ('registration_date', models.DateTimeField(null=True)),
                ('update_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'salon_items',
            },
        ),
    ]
