# Generated by Django 4.1.7 on 2023-03-25 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Saller',
            new_name='Seller',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='saller_name',
            new_name='seller_name',
        ),
        migrations.AlterModelTable(
            name='seller',
            table='seller',
        ),
    ]
