# Generated by Django 4.1.7 on 2023-03-25 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0004_rename_usage_amount_emoney_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freeedeals',
            old_name='title_row',
            new_name='title',
        ),
    ]
