# Generated by Django 4.1.7 on 2023-03-25 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0006_rename_gift_count_omron_gift_ticket_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='from_date',
            new_name='from_time',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='to_date',
            new_name='to_time',
        ),
    ]
