# Generated by Django 4.1.7 on 2023-03-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0007_rename_from_date_sales_from_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='sales_date',
        ),
    ]
