# Generated by Django 4.1.7 on 2023-03-26 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0009_payments_id_alter_payments_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='sales_id',
            new_name='code',
        ),
    ]
