# Generated by Django 4.1.7 on 2023-03-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0010_rename_sales_id_sales_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesdetails',
            old_name='item_id',
            new_name='salon_item_id',
        ),
    ]
