# Generated by Django 4.1.7 on 2023-03-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0011_rename_item_id_salesdetails_salon_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdetails',
            name='retail_item_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
