# Generated by Django 4.1.7 on 2023-03-26 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0012_salesdetails_retail_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdetails',
            name='retail_item_id',
        ),
        migrations.RemoveField(
            model_name='salesdetails',
            name='salon_item_id',
        ),
        migrations.AddField(
            model_name='salesdetails',
            name='retail_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales_management.retailitems'),
        ),
        migrations.AddField(
            model_name='salesdetails',
            name='salon_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales_management.salonitems'),
        ),
    ]
