# Generated by Django 4.1.7 on 2023-03-26 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0013_remove_salesdetails_retail_item_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='sales_id',
        ),
        migrations.AddField(
            model_name='payments',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_payment', to='sales_management.sales'),
        ),
        migrations.AddField(
            model_name='payments',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_related', to='sales_management.sales'),
        ),
    ]
