# Generated by Django 4.1.7 on 2023-03-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0014_remove_payments_payment_id_remove_payments_sales_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='payment',
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
