# Generated by Django 4.1.7 on 2023-03-26 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0015_remove_payments_payment_payments_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdetails',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='salesdetails',
            name='sale_id',
        ),
        migrations.AddField(
            model_name='salesdetails',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_details_payment', to='sales_management.sales'),
        ),
        migrations.AddField(
            model_name='salesdetails',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales_management.sales'),
        ),
    ]
