# Generated by Django 4.1.7 on 2023-03-26 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0016_remove_salesdetails_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emoney',
            name='sales_id',
        ),
        migrations.RemoveField(
            model_name='emoney',
            name='type_id',
        ),
        migrations.AddField(
            model_name='emoney',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales_management.sales'),
        ),
        migrations.AddField(
            model_name='emoney',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales_management.emoneytype'),
        ),
    ]
