# Generated by Django 4.1.7 on 2023-03-26 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0019_remove_hp_sales_id_hp_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hp',
            name='sale',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hp', to='sales_management.sales'),
        ),
    ]
