# Generated by Django 4.1.7 on 2023-03-26 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0020_alter_hp_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emoney',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emoney', to='sales_management.sales'),
        ),
        migrations.AlterField(
            model_name='emoney',
            name='type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emoney_type', to='sales_management.emoneytype'),
        ),
    ]
