# Generated by Django 4.1.7 on 2023-03-26 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0022_alter_retailitems_seller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='date',
        ),
    ]
