# Generated by Django 4.1.7 on 2023-03-26 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0025_alter_salesdetails_retail_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emoney',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emoney', to='sales_management.emoneytype'),
        ),
    ]
