# Generated by Django 4.1.7 on 2023-03-26 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0026_alter_emoney_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hp',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hp', to='sales_management.sales'),
        ),
    ]
