# Generated by Django 4.1.7 on 2023-03-27 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0027_alter_hp_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='sales_management.sales'),
        ),
    ]
