# Generated by Django 4.1.7 on 2023-03-28 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0031_alter_salesdetails_payment_alter_salesdetails_sale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EMoneyType',
            new_name='EmoneyTypes',
        ),
        migrations.RenameModel(
            old_name='Hp',
            new_name='HPs',
        ),
        migrations.RenameModel(
            old_name='Omron',
            new_name='OmronTransactions',
        ),
        migrations.RenameModel(
            old_name='Seller',
            new_name='Sellers',
        ),
        migrations.AlterModelTable(
            name='hps',
            table='hps',
        ),
        migrations.AlterModelTable(
            name='omrontransactions',
            table='omron_transactions',
        ),
        migrations.AlterModelTable(
            name='sellers',
            table='sellers',
        ),
    ]
