# Generated by Django 4.1.7 on 2023-03-29 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0033_alter_hps_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailitems',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_items', to='sales_management.sellers'),
        ),
    ]
