# Generated by Django 4.1.7 on 2023-03-31 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0034_alter_retailitems_seller'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emoney',
            table='emoney',
        ),
        migrations.AlterModelTable(
            name='emoneytypes',
            table='emoney_types',
        ),
    ]
