# Generated by Django 4.1.7 on 2023-03-31 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0035_alter_emoney_table_alter_emoneytypes_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesDetails',
            new_name='SalesItems',
        ),
        migrations.AlterModelTable(
            name='salesitems',
            table='sales_items',
        ),
    ]
