# Generated by Django 4.1.7 on 2023-04-02 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0036_rename_salesdetails_salesitems_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitems',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_items', to='sales_management.sales'),
        ),
        migrations.AlterField(
            model_name='salesitems',
            name='retail_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salon_items', to='sales_management.retailitems'),
        ),
        migrations.AlterField(
            model_name='salesitems',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='sales_management.sales'),
        ),
        migrations.AlterField(
            model_name='salesitems',
            name='salon_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salon_items', to='sales_management.salonitems'),
        ),
    ]
