# Generated by Django 4.1.7 on 2023-04-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_management', '0038_alter_salesitems_retail_item_alter_salesitems_sale_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retailitems',
            old_name='vat_type',
            new_name='vat_category',
        ),
    ]
